#!/bin/bash

mkdir -p ~/.config/nvim
ln -s ~/.dotfiles/_nvimrc ~/.config/nvim/init.vim

sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install -y neovim python-dev python-pip python3-dev python3-pip
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
#sudo update-alternatives --config vi
#sudo update-alternatives --config vim
#sudo update-alternatives --config editor

mkdir -p ~/.config/nvim/autoload
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# put into .bashrc
echo "export NVIM_TUI_ENABLE_CURSOR_SHAPE=1" >> ~/.bashrc

vim -c ":PlugInstall"

