#!/bin/bash

mkdir -p ~/.config
ln -s ~/.dotfiles/nvim ~/.config/nvim

# need lastest node / npm
sudo apt update
sudo apt install -y nodejs npm

sudo apt install ripgrep

# build vim from src
cd
sudo apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl
git clone https://github.com/neovim/neovim.git
cd neovim
# git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

# neovim all the things
CUSTOM_NVIM_PATH=/usr/local/bin/nvim
sudo update-alternatives --install /usr/bin/ex ex "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/vi vi "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/view view "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/vim vim "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/vimdiff vimdiff "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --install /usr/bin/editor editor "${CUSTOM_NVIM_PATH}" 110
sudo update-alternatives --set ex "${CUSTOM_NVIM_PATH}"
sudo update-alternatives --set vi "${CUSTOM_NVIM_PATH}"
sudo update-alternatives --set view "${CUSTOM_NVIM_PATH}"
sudo update-alternatives --set vim "${CUSTOM_NVIM_PATH}"
sudo update-alternatives --set vimdiff "${CUSTOM_NVIM_PATH}"
sudo update-alternatives --set editor "${CUSTOM_NVIM_PATH}"


echo "Configuring vim"
# run headless to get packer and all plugins running
vi --headless
# another run to install treesitter and language servers
vi -c ":MasonInstall eslint bashls jsonls pyright tsserver tailwindcss"

